### ISSUE TITLE
small/quadratic version

### ISSUE THREAD

**Issue by freaktechnik** [mozillach/mozillach_branding#1]
It would be nice to have a shorter version. I'll have a look over the branding guidelines of what we shouldn't do, and try to avoid most of it. I'm curently thinking of doing just something like m.ch with interesting typographical alignment.

**Comment by MichaelKohler** [comment]
mh, I'm not sure if m.ch wouldn't be confusing.. and for the m, please take care that it doesn't look like the M&M branding, we need to avoid that.

I'd go for mozilla.ch as we have it as big logo, just smaller. Not sure if that will still be readable though. Please get in touch with me once you have a draft and I'll give my feedback. I can also change the Twitter avatar and the avatar here.

**Comment by stefanfreeston** [comment]
Maybe ask Elio (Mozilla Rep ) to design you one

**Comment by MichaelKohler** [comment]
I think those are good for general use: http://marco.dilbert.ch/mozilla.ch_favicon_test.htm

What do you all think?

**Comment by ghost** [comment]
I just changed the comments to make it clear, that this version is suitable for use as a logo/avatar (as opposed to the favicon, which still needs some tweaking). You can download the resulting file from http://marco.dilbert.ch/moz_logo.svg.

I can add a small web tool to generate png files in selectable sizes, if you think that would make our life easier.

**Comment by freaktechnik** [comment]
I'll add it to this repo, if that's fine with you. Do you have any specific or a freeform license in mind?

**Comment by ghost** [comment]
Yes, that's ok.
Just use whatever license we already have in place for the other stuff
as long as it's a liberal one (as in ISC, MIT, BSD, Apache, Mozilla, etc.).
And copyright by Mozilla Switzerland or mozilla.ch (not me in particular).

**Comment by freaktechnik** [comment]
The other stuff is technically under a CC-BY-3.0 license, since it's derived from a file under it, which doesn't make sense. I'll use the MPL-2.0 then like mozilla does for their svg versions of logos (if they exist).
EDIT: or does the logo use the m from the mozilla in the wordmarks? Because then we probably have to keep the CC.

**Comment by ghost** [comment]
No, it's just a look-alike designed from scratch (for simplicity). So your choice of license should be fine.

Just a minor nit:
If you want to combine tha path tag on a single line, you may also want to collapse the multiple spaces it contains. Because otherwise line #15 becomes very long.

**Comment by freaktechnik** [comment]
> Just a minor nit:
> If you want to combine tha path tag on a single line, you may also want to collapse the multiple spaces it contains. Because otherwise line #15 becomes very long.

Uh, I didn't do anything actively. Probably a CRLF to LF conversion in git that failed.
EDIT: Oh, or Firefox that didn't save the actual file but some interpretation of it..
