### ISSUE TITLE
Mozilla Wordmark not under a CC License

### ISSUE THREAD

**Issue by elioqoshi** [mozillach/mozillach_branding#2]
Logos are in most cases not under a Creative Commons license. They are either under a general copyright, registered or trademarked. The Mozilla logo falls under the latter.

In the ReadMe here it says:
"The vector version of the Mozilla wordmark is lincesed under the CC-BY-3.0 License and was created by Mozilla."

Please note that "All rights to the trademark belong to Mozilla" or something similar

**Comment by freaktechnik** [comment]
as far as I recall I copied the license from the branding page thing. I'll add the copyright notice.

**Comment by elioqoshi** [comment]
Yeah, but trademarks don't fall under "Content"
Mozilla websites usually mention "Content is licensed under a CC license blah blah"

Just a nitpick though :)

**Comment by freaktechnik** [comment]
From https://www.mozilla.org/en-US/styleguide/identity/mozilla/branding/:

> The logo files containing our trademarks are available under the following copyright licenses: vector logo files under CC-BY 3.0 or later; bitmap logo files under MPL 2.

**Comment by freaktechnik** [comment]
which concerns the markup inside the svg and not the shape of appearance, sure.

**Comment by elioqoshi** [comment]
I'm utterly confused by this, doesn't make much sense, will check that out (f.e: I am certain the actual Firefox logo is trademarked)

**Comment by freaktechnik** [comment]
Yes, but the code creating it is under the CC license.

**Comment by elioqoshi** [comment]
It's not advised to use CC for code, so still, that's a weird decision.

**Comment by freaktechnik** [comment]
Oh wait, they give you the EPS and we converted that to an SVG...
Edit: and due to the ShareAlike part of CC, the SVG is also under the CC-BY-3.0 license.

**Comment by freaktechnik** [comment]
I've added a trademark notice to the readme.
